sudo: false
language: node_js
node_js:
  - '10'

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - GITHUB_REPO: 'alajfit/vuex-action-init'

branches:
  only:
    - master

stages:
  - test

jobs:
  include:
    - stage: test
      name: 'Test ➔ Lint'
      install: travis_wait npm ci --verbose
      script: npm run lint
    - name: 'Test ➔ Unit'
      install: 
        - travis_wait npm ci --verbose
        - npm install -g codecov
      script: 
        - npm run test
        - codecov
    - name: 'Test ➔ Build'
      install: travis_wait npm ci --verbose
      script: npm run build